// Query key factory for TanStack Query
// Centralized key management ensures consistent cache invalidation

export const queryKeys = {
  courses: {
    all: ['courses'],
    list: (params) => ['courses', 'list', params],
    detail: (id) => ['courses', 'detail', id],
    lessons: (id) => ['courses', 'lessons', id],
    progress: (id) => ['courses', 'progress', id],
    enrollment: (id) => ['courses', 'enrollment', id],
    enrollments: (id) => ['courses', 'enrollments', id],
    completionCounts: (id) => ['courses', 'completionCounts', id],
    stat: () => ['courses', 'stat'],
  },
  lessons: {
    all: ['lessons'],
    detail: (id) => ['lessons', 'detail', id],
    blocks: (id) => ['lessons', 'blocks', id],
    completions: (courseId) => ['lessons', 'completions', courseId],
  },
  assignments: {
    all: ['assignments'],
    list: (lessonId) => ['assignments', 'list', lessonId],
    detail: (id) => ['assignments', 'detail', id],
    submissions: (id) => ['assignments', 'submissions', id],
    attachments: (id) => ['assignments', 'attachments', id],
    enrolledUsers: (id) => ['assignments', 'enrolledUsers', id],
    enrolledTeams: (id) => ['assignments', 'enrolledTeams', id],
  },
  events: {
    all: ['events'],
    list: (params) => ['events', 'list', params],
    detail: (id) => ['events', 'detail', id],
    attendees: (id) => ['events', 'attendees', id],
    attendeeCount: (id) => ['events', 'attendeeCount', id],
    stats: (id) => ['events', 'stats', id],
    user: () => ['events', 'user'],
    userAttendees: () => ['events', 'userAttendees'],
    upcoming: () => ['events', 'upcoming'],
  },
  notifications: {
    all: ['notifications'],
    list: () => ['notifications', 'list'],
    unread: () => ['notifications', 'unread'],
    summary: () => ['notifications', 'summary'],
    detail: (id) => ['notifications', 'detail', id],
    preferences: () => ['notifications', 'preferences'],
  },
  teams: {
    all: ['teams'],
    list: (params) => ['teams', 'list', params],
    detail: (id) => ['teams', 'detail', id],
    members: (id) => ['teams', 'members', id],
    availableUsers: (id) => ['teams', 'availableUsers', id],
    stat: () => ['teams', 'stat'],
  },
  users: {
    all: ['users'],
    list: (params) => ['users', 'list', params],
    detail: (id) => ['users', 'detail', id],
    stat: () => ['users', 'stat'],
  },
  categories: {
    all: ['categories'],
    list: (params) => ['categories', 'list', params],
    detail: (id) => ['categories', 'detail', id],
    stat: () => ['categories', 'stat'],
  },
  learningPaths: {
    all: ['learningPaths'],
    list: (params) => ['learningPaths', 'list', params],
    detail: (id) => ['learningPaths', 'detail', id],
    progress: (id) => ['learningPaths', 'progress', id],
    enrollments: (id) => ['learningPaths', 'enrollments', id],
    categories: () => ['learningPaths', 'categories'],
    stat: () => ['learningPaths', 'stat'],
  },
  enrollments: {
    all: ['enrollments'],
    my: () => ['enrollments', 'my'],
  },
  stats: {
    all: ['stats'],
    dashboard: () => ['stats', 'dashboard'],
  },
};
