/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * MeroEdu API
 * MeroEdu Learning Management System (LMS) API Backend.
 * OpenAPI spec version: 2.0
 */
export interface DomainAIGenerationRequest {
  blockType: string;
  context?: string;
  lessonId: number;
  prompt: string;
}

export interface DomainActivityLog {
  action?: string;
  createdAt?: number;
  entityId?: number;
  entityType?: string;
  id?: number;
  ipAddress?: string;
  metadata?: string;
  organizationId?: number;
  sessionId?: string;
  userAgent?: string;
  userId?: number;
}

export interface DomainAdminEnrollTeamRequest {
  teamId: number;
}

export interface DomainAdminEnrollUserRequest {
  userId: number;
}

export interface DomainAdminResetPasswordRequest {
  /** @minLength 6 */
  newPassword: string;
  userId: number;
}

export interface DomainAssignmentAttachment {
  assignmentId?: number;
  createdAt?: string;
  id?: number;
  mediaId?: number;
}

export interface DomainAssignmentEnrollment {
  assignmentId?: number;
  enrolledAt?: string;
  enrolledBy?: number;
  id?: number;
  userId?: number;
}

export interface DomainAssignmentTeamEnrollment {
  assignmentId?: number;
  enrolledAt?: string;
  enrolledBy?: number;
  id?: number;
  teamId?: number;
}

export interface DomainAttachment {
  courseId?: number;
  createdAt?: string;
  description?: string;
  fileSize?: number;
  fileType?: string;
  id?: number;
  name?: string;
  title?: string;
  updatedAt?: string;
}

export type DomainAttendeeStatus = typeof DomainAttendeeStatus[keyof typeof DomainAttendeeStatus];


export const DomainAttendeeStatus = {
  AttendeeStatusInvited: 'invited',
  AttendeeStatusAccepted: 'accepted',
  AttendeeStatusDeclined: 'declined',
  AttendeeStatusTentative: 'tentative',
  AttendeeStatusAttended: 'attended',
  AttendeeStatusMissed: 'missed',
} as const;

export interface DomainAuditLog {
  action?: string;
  createdAt?: string;
  entityId?: number;
  entityType?: string;
  id?: number;
  ipAddress?: string;
  newValue?: string;
  oldValue?: string;
  organizationId?: number;
  userAgent?: string;
  userId?: number;
}

export interface DomainCategory {
  color?: string;
  courseCount?: number;
  createdAt?: string;
  depth?: number;
  description?: string;
  icon?: string;
  id?: number;
  imageUrl?: string;
  name: string;
  parentId?: number;
  slug?: string;
  sortOrder?: number;
  status?: number;
  updatedAt?: string;
}

export type DomainCertificateOrientation = typeof DomainCertificateOrientation[keyof typeof DomainCertificateOrientation];


export const DomainCertificateOrientation = {
  CertificateOrientationLandscape: 'landscape',
  CertificateOrientationPortrait: 'portrait',
} as const;

export interface DomainContentRevision {
  blockId?: string;
  createdAt?: string;
  createdBy?: number;
  id?: number;
  lessonId?: number;
  revision?: number;
  snapshot?: string;
}

export type DomainContentType = typeof DomainContentType[keyof typeof DomainContentType];


export const DomainContentType = {
  ContentTypeMarkdown: 'markdown',
  ContentTypeHTML: 'html',
  ContentTypePlain: 'plain',
} as const;

export type DomainCourseEnrollmentType = typeof DomainCourseEnrollmentType[keyof typeof DomainCourseEnrollmentType];


export const DomainCourseEnrollmentType = {
  open: 'open',
  approval: 'approval',
  invite_only: 'invite_only',
  paid: 'paid',
} as const;

export interface DomainUser {
  address1?: string;
  address2?: string;
  avatar?: string;
  bio?: string;
  countryId?: number;
  createdAt?: string;
  deletedAt?: string;
  email?: string;
  emailVerified?: boolean;
  emailVerifiedAt?: string;
  firstname?: string;
  id?: number;
  invitedBy?: number;
  joinedDate?: string;
  lastLoginAt?: string;
  lastOnline?: string;
  lastname?: string;
  loginCount?: number;
  organizationId?: number;
  password?: string;
  permissions?: string[];
  phone?: string;
  preferredLanguage?: string;
  role?: string;
  roleId?: number;
  status?: number;
  updatedAt?: string;
  username?: string;
}

export interface DomainNullInt64 {
  int64?: number;
  valid?: boolean;
}

export interface DomainLesson {
  contentFormat?: string;
  courseId?: number;
  createdAt?: string;
  displayOrder?: number;
  durationMinutes?: number;
  id?: number;
  isFreePreview?: boolean;
  lessonType?: string;
  status?: number;
  title: string;
  updatedAt?: string;
}

export type DomainStatus = typeof DomainStatus[keyof typeof DomainStatus];


export const DomainStatus = {
  Success: 'success',
  Error: 'error',
  CourseInDraft: 'draft',
  CourseArchived: 'archived',
  CourseAssigned: 'assigned',
  CoursePublished: 'published',
  CoursePublic: 'public',
  CourseCreated: 'created',
  CourseComplete: 'completed',
  StatusSuccess: 'queued',
  StatusQueued: 'sending',
  StatusSending: 'unknown',
  StatusUnknown: 'scheduled',
  StatusScheduled: 'retrying',
} as const;

export interface DomainCourse {
  attachments?: DomainAttachment[];
  author?: DomainUser;
  authorId?: DomainNullInt64;
  categories?: DomainCategory;
  categoryId?: DomainNullInt64;
  certificateEnabled?: boolean;
  /**
     * @minimum 0
     * @maximum 100
     */
  completionThreshold?: number;
  createdAt?: string;
  deletedAt?: string;
  deletedBy?: number;
  /** @maxLength 5000 */
  description?: string;
  /** @minimum 0 */
  duration?: number;
  enrollmentType?: DomainCourseEnrollmentType;
  featured?: boolean;
  id?: number;
  imageUrl?: string;
  lessonCount?: number;
  lessons?: DomainLesson[];
  longDescription?: string;
  status?: DomainStatus;
  thumbnailUrl?: string;
  /**
     * @minLength 3
     * @maxLength 256
     */
  title: string;
  updatedAt?: string;
  users?: DomainUser[];
  version?: number;
}

export interface DomainCourseInsights {
  activeEnrollments?: number;
  avgProgressPercent?: number;
  avgQuizScore?: number;
  avgTimeSpentSec?: number;
  completedEnrollments?: number;
  courseId?: number;
  id?: number;
  quizPassRate?: number;
  refreshedAt?: number;
  totalEnrollments?: number;
  totalLessonCompletions?: number;
  totalQuizAttempts?: number;
}

export type DomainPrerequisiteType = typeof DomainPrerequisiteType[keyof typeof DomainPrerequisiteType];


export const DomainPrerequisiteType = {
  PrerequisiteTypeRequired: 'required',
  PrerequisiteTypeRecommended: 'recommended',
} as const;

export interface DomainCoursePrerequisite {
  courseId?: number;
  createdAt?: string;
  id?: number;
  prerequisiteCourseId?: number;
  prerequisiteType?: DomainPrerequisiteType;
}

export type DomainCourseUpdateDTOEnrollmentType = typeof DomainCourseUpdateDTOEnrollmentType[keyof typeof DomainCourseUpdateDTOEnrollmentType];


export const DomainCourseUpdateDTOEnrollmentType = {
  open: 'open',
  approval: 'approval',
  invite_only: 'invite_only',
  paid: 'paid',
} as const;

export interface DomainCourseUpdateDTO {
  authorId?: number;
  categoryId?: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  completionThreshold?: number;
  /** @maxLength 5000 */
  description?: string;
  /** @minimum 0 */
  duration?: number;
  enrollmentType?: DomainCourseUpdateDTOEnrollmentType;
  imageUrl?: string;
  isCertificateEnabled?: boolean;
  isFeatured?: boolean;
  longDescription?: string;
  status?: DomainStatus;
  thumbnailUrl?: string;
  /**
     * @minLength 3
     * @maxLength 256
     */
  title?: string;
  version?: number;
}

export interface DomainCourseVersion {
  changeLog?: string;
  courseId?: number;
  createdAt?: string;
  createdBy?: number;
  description?: string;
  id?: number;
  snapshot?: string;
  title?: string;
  version?: number;
}

export interface DomainCreateCertificateRequest {
  courseId: number;
  expiresAt?: string;
  grade?: string;
  issuedAt?: string;
  organizationId: number;
  score?: string;
  templateId?: number;
  /**
     * @minLength 1
     * @maxLength 256
     */
  title: string;
  userId: number;
  verificationCode?: string;
}

export interface DomainCreateCertificateTemplateRequest {
  cssStyles?: string;
  htmlTemplate: string;
  isDefault?: boolean;
  /**
     * @minLength 2
     * @maxLength 256
     */
  name: string;
  organizationId: number;
  orientation?: DomainCertificateOrientation;
}

export interface DomainCreateEventAttendeeRequest {
  eventId: number;
  status?: DomainAttendeeStatus;
  userId: number;
}

export type DomainEventType = typeof DomainEventType[keyof typeof DomainEventType];


export const DomainEventType = {
  EventTypeLiveSession: 'live_session',
  EventTypeOfficeHours: 'office_hours',
  EventTypeAssignmentDue: 'assignment_due',
  EventTypeQuizDue: 'quiz_due',
  EventTypeWebinar: 'webinar',
  EventTypeMeeting: 'meeting',
  EventTypeOther: 'other',
} as const;

export interface DomainCreateEventRequest {
  courseId?: number;
  description?: string;
  endTime: string;
  eventType?: DomainEventType;
  isRecurring?: boolean;
  location?: string;
  maxAttendees?: number;
  meetingUrl?: string;
  organizationId: number;
  parentEventId?: number;
  recurrenceRule?: string;
  startTime: string;
  timezone?: string;
  /**
     * @minLength 1
     * @maxLength 256
     */
  title: string;
}

export type DomainForumType = typeof DomainForumType[keyof typeof DomainForumType];


export const DomainForumType = {
  ForumTypeCourse: 'course',
  ForumTypeLesson: 'lesson',
  ForumTypeAnnouncement: 'announcement',
  ForumTypeQA: 'qa',
  ForumTypeOpen: 'open',
} as const;

export interface DomainCreateForumRequest {
  courseId: number;
  description?: string;
  forumType?: DomainForumType;
  isModerated?: boolean;
  lessonId?: number;
  /**
     * @minLength 3
     * @maxLength 256
     */
  title: string;
}

export interface DomainLearningPathCourse {
  courseId: number;
  coverImage?: string;
  description?: string;
  duration?: string;
  id?: number;
  instructor?: string;
  lessons?: number;
  /** @minimum 1 */
  order: number;
  title?: string;
}

export interface DomainCreateLearningPathRequest {
  category: string;
  color?: string;
  /** @minItems 1 */
  courses: DomainLearningPathCourse[];
  /** @minLength 10 */
  description: string;
  difficulty?: string;
  estimatedDuration?: string;
  image?: string;
  status?: string;
  tags?: string[];
  /**
     * @minLength 3
     * @maxLength 255
     */
  title: string;
}

export interface DomainCreateNotificationPreferenceRequest {
  email?: boolean;
  inApp?: boolean;
  notificationType: string;
  push?: boolean;
  userId: number;
}

export type DomainSentVia = typeof DomainSentVia[keyof typeof DomainSentVia];


export const DomainSentVia = {
  SentViaInApp: 'in_app',
  SentViaEmail: 'email',
  SentViaPush: 'push',
} as const;

export type DomainNotificationType = typeof DomainNotificationType[keyof typeof DomainNotificationType];


export const DomainNotificationType = {
  NotificationTypeAssignmentDue: 'assignment_due',
  NotificationTypeGradePosted: 'grade_posted',
  NotificationTypeReply: 'reply',
  NotificationTypeBadge: 'badge',
  NotificationTypeCourseUpdated: 'course_updated',
  NotificationTypeEnrollment: 'enrollment',
  NotificationTypeMention: 'mention',
  NotificationTypeSystem: 'system',
} as const;

export interface DomainCreateNotificationRequest {
  actionUrl?: string;
  body?: string;
  entityId?: number;
  entityType?: string;
  organizationId?: number;
  sentVia?: DomainSentVia[];
  /**
     * @minLength 1
     * @maxLength 256
     */
  title: string;
  type: DomainNotificationType;
  userId: number;
}

export interface DomainCreateReplyRequest {
  content: string;
  contentType?: DomainContentType;
  parentId?: number;
  threadId: number;
}

export interface DomainCreateThreadRequest {
  content: string;
  contentType?: DomainContentType;
  forumId: number;
  /**
     * @minLength 3
     * @maxLength 512
     */
  title: string;
}

export interface DomainDiscussionForum {
  courseId?: number;
  createdAt?: string;
  createdBy?: number;
  description?: string;
  forumType?: DomainForumType;
  id?: number;
  isArchived?: boolean;
  isModerated?: boolean;
  lessonId?: number;
  sortOrder?: number;
  title?: string;
  updatedAt?: string;
}

export interface DomainDiscussionReply {
  attachmentUrls?: string;
  content?: string;
  contentType?: DomainContentType;
  createdAt?: string;
  deletedAt?: string;
  id?: number;
  isAnswer?: boolean;
  parentId?: number;
  threadId?: number;
  updatedAt?: string;
  upvotes?: number;
  userId?: number;
}

export interface DomainDiscussionThread {
  attachmentUrls?: string;
  content?: string;
  contentType?: DomainContentType;
  courseId?: number;
  createdAt?: string;
  deletedAt?: string;
  forumId?: number;
  id?: number;
  isAnswered?: boolean;
  isLocked?: boolean;
  isPinned?: boolean;
  lastReplyAt?: string;
  replyCount?: number;
  title?: string;
  updatedAt?: string;
  upvotes?: number;
  userId?: number;
  viewCount?: number;
}

export type DomainEnrollmentPolicyType = typeof DomainEnrollmentPolicyType[keyof typeof DomainEnrollmentPolicyType];


export const DomainEnrollmentPolicyType = {
  EnrollmentPolicyOpen: 'open',
  EnrollmentPolicyApproval: 'approval',
  EnrollmentPolicyInvite: 'invite_only',
  EnrollmentPolicyPaid: 'paid',
} as const;

export interface DomainEnrollmentPolicy {
  completionCertificate?: boolean;
  courseId?: number;
  createdAt?: string;
  enrollmentEndAt?: number;
  enrollmentStartAt?: number;
  enrollmentType?: DomainEnrollmentPolicyType;
  id?: number;
  isRequiresPrerequisites?: boolean;
  maxEnrollments?: number;
  updatedAt?: string;
  welcomeMessage?: string;
}

export type DomainExportRequestStatus = typeof DomainExportRequestStatus[keyof typeof DomainExportRequestStatus];


export const DomainExportRequestStatus = {
  ExportRequestStatusPending: 'pending',
  ExportRequestStatusProcessing: 'processing',
  ExportRequestStatusCompleted: 'completed',
  ExportRequestStatusFailed: 'failed',
} as const;

export type DomainInvitationRole = typeof DomainInvitationRole[keyof typeof DomainInvitationRole];


export const DomainInvitationRole = {
  InvitationRoleLearner: 'learner',
  InvitationRoleAdmin: 'admin',
  InvitationRoleInstructor: 'instructor',
} as const;

export type DomainInvitationStatus = typeof DomainInvitationStatus[keyof typeof DomainInvitationStatus];


export const DomainInvitationStatus = {
  InvitationStatusPending: 'pending',
  InvitationStatusAccepted: 'accepted',
  InvitationStatusExpired: 'expired',
  InvitationStatusRevoked: 'revoked',
} as const;

export interface DomainInvitation {
  acceptedAt?: string;
  acceptedBy?: number;
  courseId?: number;
  createdAt?: string;
  email?: string;
  expiresAt?: string;
  id?: number;
  invitedBy?: number;
  organizationId?: number;
  role?: DomainInvitationRole;
  status?: DomainInvitationStatus;
  token?: string;
  uuid?: string;
}

export interface DomainLearnerProgressSummary {
  assignmentsGraded?: number;
  assignmentsSubmitted?: number;
  avgAssignmentScore?: number;
  avgQuizScore?: number;
  completedLessons?: number;
  courseId?: number;
  id?: number;
  lastActivityAt?: number;
  overallProgress?: number;
  quizzesPassed?: number;
  totalAssignments?: number;
  totalLessons?: number;
  totalQuizzes?: number;
  totalTimeSpentSec?: number;
  updatedAt?: number;
  userId?: number;
}

export interface DomainLearnerStreak {
  currentStreakDays?: number;
  id?: number;
  lastActivityDate?: string;
  longestStreakDays?: number;
  refreshedAt?: number;
  totalActiveDays?: number;
  userId?: number;
}

export type DomainLearningPathDifficulty = typeof DomainLearningPathDifficulty[keyof typeof DomainLearningPathDifficulty];


export const DomainLearningPathDifficulty = {
  Beginner: 'Beginner',
  Intermediate: 'Intermediate',
  Advanced: 'Advanced',
  Beginner_to_Advanced: 'Beginner to Advanced',
} as const;

export type DomainLearningPathStatus = typeof DomainLearningPathStatus[keyof typeof DomainLearningPathStatus];


export const DomainLearningPathStatus = {
  draft: 'draft',
  published: 'published',
  archived: 'archived',
} as const;

export interface DomainLearningPath {
  authorId?: number;
  authorName?: string;
  category: string;
  color?: string;
  /** @minItems 1 */
  courses?: DomainLearningPathCourse[];
  createdAt?: string;
  /** @minLength 10 */
  description: string;
  difficulty?: DomainLearningPathDifficulty;
  enrolledCount?: number;
  estimatedDuration?: string;
  id?: number;
  image?: string;
  rating?: number;
  status?: DomainLearningPathStatus;
  tags?: string[];
  /**
     * @minLength 3
     * @maxLength 255
     */
  title: string;
  totalCourses?: number;
  updatedAt?: string;
}

export interface DomainLearningPathCompletedCourse {
  completedAt?: string;
  courseId?: number;
  title?: string;
}

export type DomainLearningPathEnrollmentStatus = typeof DomainLearningPathEnrollmentStatus[keyof typeof DomainLearningPathEnrollmentStatus];


export const DomainLearningPathEnrollmentStatus = {
  active: 'active',
  completed: 'completed',
  dropped: 'dropped',
} as const;

export interface DomainLearningPathRemainingCourse {
  courseId?: number;
  title?: string;
}

export interface DomainLearningPathEnrollment {
  completedAt?: string;
  completedCourses?: DomainLearningPathCompletedCourse[];
  currentCourseId?: number;
  currentCourseTitle?: string;
  enrolledAt?: string;
  estimatedCompletion?: string;
  id?: number;
  lastAccessed?: string;
  learningPathId?: number;
  progress?: number;
  remainingCourses?: DomainLearningPathRemainingCourse[];
  status?: DomainLearningPathEnrollmentStatus;
  userId?: number;
}

export interface DomainLearningPathListResponse {
  limit?: number;
  page?: number;
  paths?: DomainLearningPath[];
  total?: number;
  totalPages?: number;
}

export interface DomainLessonBlockRequest {
  lessonId: number;
  snapshot: string;
}

export interface DomainLessonPrerequisite {
  createdAt?: string;
  id?: number;
  lessonId?: number;
  prerequisiteLessonId?: number;
  prerequisiteType?: DomainPrerequisiteType;
}

export interface DomainLoginRequest {
  email: string;
  password: string;
}

export interface DomainUserResponse {
  avatar?: string;
  bio?: string;
  createdAt?: string;
  email?: string;
  emailVerified?: boolean;
  firstName?: string;
  id?: number;
  lastLoginAt?: string;
  lastName?: string;
  lastOnline?: string;
  loginCount?: number;
  permissions?: string[];
  phone?: string;
  preferredLanguage?: string;
  role?: string;
  status?: number;
  updatedAt?: string;
  username?: string;
}

export interface DomainLoginResponse {
  token?: string;
  user?: DomainUserResponse;
}

export interface DomainMediaFolder {
  createdAt?: string;
  createdBy?: number;
  id?: number;
  name?: string;
  organizationId?: number;
  parentId?: number;
  slug?: string;
}

export interface DomainOrgInsights {
  activeLearners30d?: number;
  activeLearners7d?: number;
  avgCourseProgress?: number;
  completedEnrollments?: number;
  id?: number;
  organizationId?: number;
  publishedCourses?: number;
  refreshedAt?: number;
  totalCourses?: number;
  totalEnrollments?: number;
  totalLearners?: number;
}

export type DomainPaginatedResponseData = { [key: string]: unknown };

export interface DomainPaginatedResponse {
  data?: DomainPaginatedResponseData;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
}

export interface DomainPasswordChangeRequest {
  currentPassword: string;
  /** @minLength 6 */
  newPassword: string;
}

export interface DomainProfileUpdateRequest {
  avatar?: string;
  bio?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
}

export interface DomainQuestionBank {
  createdAt?: number;
  createdBy?: number;
  description?: string;
  id?: number;
  organizationId?: number;
  title?: string;
  updatedAt?: number;
}

export interface DomainQuestionBankOption {
  id?: number;
  isCorrect?: boolean;
  questionId?: number;
  sortOrder?: number;
  text?: string;
}

export type DomainQuestionDifficulty = typeof DomainQuestionDifficulty[keyof typeof DomainQuestionDifficulty];


export const DomainQuestionDifficulty = {
  DifficultyEasy: 'easy',
  DifficultyMedium: 'medium',
  DifficultyHard: 'hard',
} as const;

export interface DomainQuestionBankQuestion {
  bankId?: number;
  correctAnswer?: string;
  createdAt?: number;
  createdBy?: number;
  description?: string;
  difficulty?: DomainQuestionDifficulty;
  explanation?: string;
  id?: number;
  points?: number;
  tags?: string;
  title?: string;
  /** reuses question type constants from collaboration.go */
  type?: string;
  updatedAt?: number;
}

export interface DomainQuizAnalytics {
  avgScore?: number;
  avgTimeSec?: number;
  difficultyIndex?: number;
  id?: number;
  passRate?: number;
  quizId?: number;
  totalAttempts?: number;
  uniqueAttempts?: number;
  updatedAt?: number;
}

export interface DomainReactionCount {
  count?: number;
  reaction?: string;
}

export interface DomainRegisterRequest {
  email: string;
  firstName: string;
  lastName: string;
  /** @minLength 6 */
  password: string;
  phone?: string;
}

export interface DomainReorderCoursesRequest {
  /** @minItems 1 */
  courses: DomainLearningPathCourse[];
}

export interface DomainReorderRequest {
  id: number;
  orderNumber: number;
}

export type DomainResponseData = { [key: string]: unknown };

export interface DomainResponse {
  data?: DomainResponseData;
  message?: DomainStatus;
}

export interface DomainRevokeCertificateRequest {
  /**
     * @minLength 1
     * @maxLength 500
     */
  revokeReason: string;
}

export interface DomainRole {
  code?: string;
  color?: string;
  createdAt?: string;
  description?: string;
  id?: number;
  name?: string;
  permissions?: string[];
  updatedAt?: string;
}

export interface DomainRubricLevel {
  criteriaId?: number;
  id?: number;
  points?: number;
  sortOrder?: number;
  title: string;
}

export interface DomainRubricCriteria {
  description?: string;
  id?: number;
  levels?: DomainRubricLevel[];
  maxPoints?: number;
  rubricId?: number;
  sortOrder?: number;
  title: string;
}

export interface DomainRubric {
  createdAt?: string;
  createdBy?: number;
  criteria?: DomainRubricCriteria[];
  description?: string;
  id?: number;
  isTemplate?: boolean;
  maxPoints?: number;
  organizationId?: number;
  title: string;
  updatedAt?: string;
}

export interface DomainRubricGrade {
  criteriaId?: number;
  feedback?: string;
  id?: number;
  levelId?: number;
  points?: number;
  submissionId?: number;
}

export interface DomainStatsResponse {
  categoryCount?: number;
  courseCount?: number;
  teamCount?: number;
  userCount?: number;
}

export type DomainSubmissionStatus = typeof DomainSubmissionStatus[keyof typeof DomainSubmissionStatus];


export const DomainSubmissionStatus = {
  SubmissionSubmitted: 'submitted',
  SubmissionGraded: 'graded',
  SubmissionReturned: 'returned',
} as const;

export type DomainSubmissionType = typeof DomainSubmissionType[keyof typeof DomainSubmissionType];


export const DomainSubmissionType = {
  SubmissionTypeUser: 'user',
  SubmissionTypeTeam: 'team',
} as const;

export interface DomainSubmission {
  assignmentId?: number;
  /** comma-separated file URLs */
  attachmentURLs?: string;
  attemptNumber?: number;
  /** text content or file URLs */
  content?: string;
  feedback?: string;
  gradedAt?: string;
  gradedBy?: number;
  id?: number;
  isLate?: boolean;
  score?: number;
  status?: DomainSubmissionStatus;
  /** USER or TEAM */
  submissionType?: DomainSubmissionType;
  submittedAt?: string;
  submittedBy?: number;
  teamId?: number;
  user?: DomainUser;
  userId?: number;
}

export type DomainSummariesData = { [key: string]: unknown };

export interface DomainSummaries {
  data?: DomainSummariesData;
  message?: DomainStatus;
  total?: number;
}

export interface DomainTeam {
  color?: string;
  createdAt?: string;
  description?: string;
  id?: number;
  imageUrl?: string;
  member_count?: number;
  name?: string;
  organizationId?: number;
  roleId?: number;
  status?: number;
  updatedAt?: string;
}

export interface DomainTeamMember {
  avatar?: string;
  createdAt?: string;
  id?: number;
  role?: string;
  teamId?: number;
  userEmail?: string;
  userId?: number;
  userName?: string;
}

export interface DomainThreadListResponse {
  limit?: number;
  page?: number;
  threads?: DomainDiscussionThread[];
  total?: number;
  totalPages?: number;
}

export interface DomainUpdateCertificateRequest {
  expiresAt?: number;
  grade?: string;
  isRevoked?: boolean;
  pdfUrl?: string;
  revokeReason?: string;
  score?: string;
  templateId?: number;
  title?: string;
}

export interface DomainUpdateCertificateTemplateRequest {
  cssStyles?: string;
  htmlTemplate?: string;
  isDefault?: boolean;
  name?: string;
  orientation?: DomainCertificateOrientation;
}

export interface DomainUpdateDataExportRequest {
  completedAt?: string;
  expiresAt?: string;
  fileUrl?: string;
  status?: DomainExportRequestStatus;
}

export interface DomainUpdateEventAttendeeRequest {
  status: DomainAttendeeStatus;
}

export interface DomainUpdateEventRequest {
  description?: string;
  endTime?: string;
  eventType?: DomainEventType;
  isRecurring?: boolean;
  location?: string;
  maxAttendees?: number;
  meetingUrl?: string;
  recurrenceRule?: string;
  startTime?: string;
  timezone?: string;
  title?: string;
}

export interface DomainUpdateLearningPathRequest {
  category?: string;
  color?: string;
  /** @minItems 1 */
  courses?: DomainLearningPathCourse[];
  /** @minLength 10 */
  description?: string;
  difficulty?: string;
  estimatedDuration?: string;
  image?: string;
  status?: string;
  tags?: string[];
  /**
     * @minLength 3
     * @maxLength 255
     */
  title?: string;
}

export interface DomainUpdateNotificationPreferenceRequest {
  email?: boolean;
  inApp?: boolean;
  push?: boolean;
}

export type DomainUserLearningPathEnrollmentStatus = typeof DomainUserLearningPathEnrollmentStatus[keyof typeof DomainUserLearningPathEnrollmentStatus];


export const DomainUserLearningPathEnrollmentStatus = {
  active: 'active',
  completed: 'completed',
  dropped: 'dropped',
} as const;

export interface DomainUserLearningPathEnrollment {
  completedAt?: string;
  completedCourses?: DomainLearningPathCompletedCourse[];
  courseCount?: number;
  currentCourseId?: number;
  currentCourseTitle?: string;
  description?: string;
  enrolledAt?: string;
  estimatedCompletion?: string;
  id?: number;
  imageUrl?: string;
  lastAccessed?: string;
  learningPathId?: number;
  progress?: number;
  remainingCourses?: DomainLearningPathRemainingCourse[];
  status?: DomainUserLearningPathEnrollmentStatus;
  title?: string;
  userId?: number;
}

export type DomainWaitlistStatus = typeof DomainWaitlistStatus[keyof typeof DomainWaitlistStatus];


export const DomainWaitlistStatus = {
  WaitlistStatusWaiting: 'waiting',
  WaitlistStatusInvited: 'invited',
  WaitlistStatusEnrolled: 'enrolled',
  WaitlistStatusExpired: 'expired',
} as const;

export interface DomainWaitlistEntry {
  courseId?: number;
  createdAt?: string;
  expiresAt?: string;
  id?: number;
  invitedAt?: string;
  position?: number;
  status?: DomainWaitlistStatus;
  userId?: number;
}

export interface HttpAdminEnrollRequest {
  userId: number;
}

export interface HttpAdminEnrollTeamRequest {
  teamId: number;
}

export interface HttpCompleteRequest {
  /** @minimum 0 */
  timeSpentSeconds?: number;
}

export interface HttpErrorDetail {
  constraint?: string;
  field?: string;
  message?: string;
}

export interface HttpResponseError {
  code?: string;
  details?: HttpErrorDetail[];
  message?: string;
}

export type GetCourseInsights200 = DomainResponse & {
  data?: DomainCourseInsights;
};

export type GetOrgInsights200 = DomainResponse & {
  data?: DomainOrgInsights;
};

export type ListTopStreaksParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type ListTopStreaks200 = DomainResponse & {
  data?: DomainLearnerStreak[];
};

export type GetLearnerStreak200 = DomainResponse & {
  data?: DomainLearnerStreak;
};

export type LogActivity201 = DomainResponse & {
  data?: DomainActivityLog;
};

export type GetEntityActivityParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetEntityActivity200 = DomainResponse & {
  data?: DomainActivityLog[];
};

export type GetOrgActivityParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetOrgActivity200 = DomainResponse & {
  data?: DomainActivityLog[];
};

export type GetUserActivityParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetUserActivity200 = DomainResponse & {
  data?: DomainActivityLog[];
};

export type CreateQuestionBank201 = DomainResponse & {
  data?: DomainQuestionBank;
};

export type ListQuestionBanksByOrgParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type ListQuestionBanksByOrg200 = DomainResponse & {
  data?: DomainQuestionBank[];
};

export type ListBankQuestions200 = DomainResponse & {
  data?: DomainQuestionBankQuestion[];
};

export type CreateBankQuestion201 = DomainResponse & {
  data?: DomainQuestionBankQuestion;
};

export type SearchBankQuestionsParams = {
/**
 * Search query
 */
q: string;
};

export type SearchBankQuestions200 = DomainResponse & {
  data?: DomainQuestionBankQuestion[];
};

export type GetQuestionBank200 = DomainResponse & {
  data?: DomainQuestionBank;
};

export type UpdateQuestionBank200 = DomainResponse & {
  data?: DomainQuestionBank;
};

export type UpsertProgress200 = DomainResponse & {
  data?: DomainLearnerProgressSummary;
};

export type GetCourseProgressParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetCourseProgress200 = DomainResponse & {
  data?: DomainLearnerProgressSummary[];
};

export type GetByUserProgress200 = DomainResponse & {
  data?: DomainLearnerProgressSummary[];
};

export type GetProgress200 = DomainResponse & {
  data?: DomainLearnerProgressSummary;
};

export type UpdateBankQuestion200 = DomainResponse & {
  data?: DomainQuestionBankQuestion;
};

export type GetBankOptions200 = DomainResponse & {
  data?: DomainQuestionBankOption[];
};

export type CreateBankOption201 = DomainResponse & {
  data?: DomainQuestionBankOption;
};

export type GetQuizAnalytics200 = DomainResponse & {
  data?: DomainQuizAnalytics;
};

export type UpsertQuizAnalytics200 = DomainResponse & {
  data?: DomainQuizAnalytics;
};

export type AssignmentGradeBody = { [key: string]: unknown };

export type GradeTeamBody = { [key: string]: unknown };

export type GetAttachments200 = DomainResponse & {
  data?: DomainAssignmentAttachment[];
};

export type AddAttachmentBody = { [key: string]: unknown };

export type EnrollTeamBody = { [key: string]: unknown };

export type EnrollUserBody = { [key: string]: unknown };

export type GetEnrolledTeams200 = DomainResponse & {
  data?: DomainAssignmentTeamEnrollment[];
};

export type GetEnrolledUsers200 = DomainResponse & {
  data?: DomainAssignmentEnrollment[];
};

export type AssignmentSubmitBody = { [key: string]: unknown };

export type AssignmentSubmit201 = DomainResponse & {
  data?: DomainSubmission;
};

export type SubmitTeamBody = { [key: string]: unknown };

export type SubmitTeam201 = DomainResponse & {
  data?: DomainSubmission;
};

export type AttachmentCreateBody = {
  /** Title */
  title?: string;
  /** Description */
  description?: string;
  /** Upload file */
  file: Blob;
};

export type DownloadAttachmentParams = {
/**
 * uuid-encoded file name
 */
file: string;
};

export type GetAuditLogsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
/**
 * Filter by user ID
 */
userId?: number;
/**
 * Filter by organization ID
 */
orgId?: number;
/**
 * Filter by entity type
 */
entityType?: string;
/**
 * Filter by entity ID
 */
entityId?: number;
/**
 * Filter by action
 */
action?: string;
};

export type LoginHandler200 = DomainResponse & {
  data?: DomainLoginResponse;
};

export type MeHandler200 = DomainResponse & {
  data?: DomainUserResponse;
};

export type UpdateProfileHandler200 = DomainResponse & {
  data?: DomainUserResponse;
};

export type RegisterHandler201 = DomainResponse & {
  data?: DomainUserResponse;
};

export type CategoryGetAllParams = {
/**
 * Search by name
 */
search?: string;
/**
 * Offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type CategoryGetChildrenParams = {
/**
 * Offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type CategoryGetRootsParams = {
/**
 * Offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type CategorySetParentBody = {
  parentId?: number;
};

export type GetUserCertificatesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetCourseCertificatesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetOrgCertificatesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type CreateCoursePrerequisite201 = DomainResponse & {
  data?: DomainCoursePrerequisite;
};

export type GetCoursePrerequisitesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
pageSize?: number;
};

export type GetCoursePrerequisites200 = DomainPaginatedResponse & {
  data?: DomainCoursePrerequisite[];
};

export type CreateLessonPrerequisite201 = DomainResponse & {
  data?: DomainLessonPrerequisite;
};

export type GetLessonPrerequisitesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
pageSize?: number;
};

export type GetLessonPrerequisites200 = DomainPaginatedResponse & {
  data?: DomainLessonPrerequisite[];
};

export type CreateContentRevision201 = DomainResponse & {
  data?: DomainContentRevision;
};

export type GetBlockRevisionsParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetBlockRevisions200 = DomainPaginatedResponse & {
  data?: DomainContentRevision[];
};

export type GetLatestContentRevision200 = DomainResponse & {
  data?: DomainContentRevision;
};

export type GetLessonRevisionsParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetLessonRevisions200 = DomainPaginatedResponse & {
  data?: DomainContentRevision[];
};

export type GetContentRevision200 = DomainResponse & {
  data?: DomainContentRevision;
};

export type CreateCourseVersion201 = DomainResponse & {
  data?: DomainCourseVersion;
};

export type GetCourseVersionsParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetCourseVersions200 = DomainPaginatedResponse & {
  data?: DomainCourseVersion[];
};

export type GetLatestCourseVersion200 = DomainResponse & {
  data?: DomainCourseVersion;
};

export type GetCourseVersion200 = DomainResponse & {
  data?: DomainCourseVersion;
};

export type CourseGetAllParams = {
/**
 * start
 */
start: number;
/**
 * limit
 */
limit: number;
};

export type CoursePartialUpdate200 = DomainResponse & {
  data?: DomainCourse;
};

export type ArchiveCourse200 = DomainResponse & {
  data?: DomainCourse;
};

export type ToggleImportant200 = DomainResponse & {
  data?: DomainCourse;
};

export type PublishCourse200 = DomainResponse & {
  data?: DomainCourse;
};

export type GetCourseForums200 = DomainResponse & {
  data?: DomainDiscussionForum[];
};

export type CreateForum201 = DomainResponse & {
  data?: DomainDiscussionForum;
};

export type GetForumThreadsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Thread limit per page
 */
limit?: number;
};

export type GetForumThreads200 = DomainResponse & {
  data?: DomainThreadListResponse;
};

export type CreateThread201 = DomainResponse & {
  data?: DomainDiscussionThread;
};

export type SearchThreadsParams = {
/**
 * Search query string
 */
q: string;
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
limit?: number;
};

export type SearchThreads200 = DomainResponse & {
  data?: DomainThreadListResponse;
};

export type GetForum200 = DomainResponse & {
  data?: DomainDiscussionForum;
};

export type UpdateForum200 = DomainResponse & {
  data?: DomainDiscussionForum;
};

export type ReactBody = { [key: string]: unknown };

export type RemoveReactionBody = { [key: string]: unknown };

export type GetReactions200 = DomainResponse & {
  data?: DomainReactionCount[];
};

export type GetReply200 = DomainResponse & {
  data?: DomainDiscussionReply;
};

export type UpdateReply200 = DomainResponse & {
  data?: DomainDiscussionReply;
};

export type MarkAsAnswerParams = {
/**
 * Is it correct answer
 */
isAnswer: boolean;
};

export type SubscribeBody = { [key: string]: unknown };

export type UnsubscribeBody = { [key: string]: unknown };

export type GetThread200 = DomainResponse & {
  data?: DomainDiscussionThread;
};

export type UpdateThread200 = DomainResponse & {
  data?: DomainDiscussionThread;
};

export type LockThreadParams = {
/**
 * Locked status
 */
lock: boolean;
};

export type PinThreadParams = {
/**
 * Pinned status
 */
pin: boolean;
};

export type GetThreadRepliesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Limit number
 */
limit?: number;
};

export type GetThreadReplies200 = DomainResponse & {
  data?: DomainDiscussionReply[];
};

export type CreateReply201 = DomainResponse & {
  data?: DomainDiscussionReply;
};

export type VoteBody = { [key: string]: unknown };

export type CreateInvitation201 = DomainResponse & {
  data?: DomainInvitation;
};

export type GetInvitationsByCourse200 = DomainResponse & {
  data?: DomainInvitation[];
};

export type GetPendingInvitationsByEmail200 = DomainResponse & {
  data?: DomainInvitation[];
};

export type GetInvitationByToken200 = DomainResponse & {
  data?: DomainInvitation;
};

export type GetInvitationByUUID200 = DomainResponse & {
  data?: DomainInvitation;
};

export type CreateEnrollmentPolicy201 = DomainResponse & {
  data?: DomainEnrollmentPolicy;
};

export type GetEnrollmentPolicy200 = DomainResponse & {
  data?: DomainEnrollmentPolicy;
};

export type UpdateEnrollmentPolicy200 = DomainResponse & {
  data?: DomainEnrollmentPolicy;
};

export type CreateWaitlistEntry201 = DomainResponse & {
  data?: DomainWaitlistEntry;
};

export type GetWaitlist200 = DomainResponse & {
  data?: DomainWaitlistEntry[];
};

export type InviteWaitlist200 = DomainResponse & {
  data?: DomainWaitlistEntry;
};

export type GetOrgEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetCourseEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetEventsInTimeRangeParams = {
/**
 * Start time (Unix timestamp)
 */
startTime: number;
/**
 * End time (Unix timestamp)
 */
endTime: number;
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetEventsByTypeParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetUpcomingEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetUserEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetUserAttendeesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetEventAttendeesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type LearningPathGetAllParams = {
/**
 * Search in title and description
 */
search?: string;
/**
 * Filter by category name
 */
category?: string;
/**
 * Filter by status: draft, published, archived
 */
status?: string;
/**
 * Page number (default: 1)
 */
page?: number;
/**
 * Items per page (default: 6)
 */
limit?: number;
};

export type LearningPathGetAll200 = DomainResponse & {
  data?: DomainLearningPathListResponse;
};

export type LearningPathCreate201 = DomainResponse & {
  data?: DomainLearningPath;
};

export type GetCategories200 = DomainResponse & {
  data?: string[];
};

export type GetMyLearningPathEnrollmentsParams = {
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type GetMyLearningPathEnrollments200 = DomainResponse & {
  data?: DomainUserLearningPathEnrollment[];
};

export type LearningPathGetStatParams = {
/**
 * Search in title and description
 */
search?: string;
/**
 * Filter by category
 */
category?: string;
/**
 * Filter by status
 */
status?: string;
};

export type LearningPathGetByID200 = DomainResponse & {
  data?: DomainLearningPath;
};

export type LearningPathUpdate200 = DomainResponse & {
  data?: DomainLearningPath;
};

export type LearningPathAdminEnrollTeam200Data = {[key: string]: number};

export type LearningPathAdminEnrollTeam200 = DomainResponse & {
  data?: LearningPathAdminEnrollTeam200Data;
};

export type LearningPathAdminEnrollUser200 = DomainResponse & {
  data?: DomainLearningPathEnrollment;
};

export type GetLPEnrollments200 = DomainResponse & {
  data?: DomainLearningPathEnrollment[];
};

export type LearningPathEnroll200 = DomainResponse & {
  data?: DomainLearningPathEnrollment;
};

export type LearningPathGetProgress200 = DomainResponse & {
  data?: DomainLearningPathEnrollment;
};

export type LessonGetAllParams = {
/**
 * start
 */
start: number;
/**
 * limit
 */
limit: number;
};

export type UploadBlockMediaBody = {
  /** Media file to upload */
  file: Blob;
};

export type UploadLessonMediaBody = {
  /** Media file to upload */
  file: Blob;
};

export type GetFoldersParams = {
/**
 * Parent folder ID for nested folders
 */
parentId?: number;
};

export type MediaUploadBody = {
  /** File to upload */
  file: Blob;
  /** Entity type (block, attachment, avatar, course, team) */
  entity_type?: string;
  /** Entity ID */
  entity_id?: number;
  /** Content type hint (image, video, audio, document) */
  content_type?: string;
};

export type GetAllRolesHandler200 = DomainResponse & {
  data?: DomainRole[];
};

export type CreateRoleHandler201 = DomainResponse & {
  data?: DomainRole;
};

export type GetRoleByIDHandler200 = DomainResponse & {
  data?: DomainRole;
};

export type UpdateRoleHandler200 = DomainResponse & {
  data?: DomainRole;
};

export type ListRubricsParams = {
/**
 * Limit results
 */
limit?: number;
/**
 * Offset results
 */
offset?: number;
};

export type ListRubrics200 = DomainResponse & {
  data?: DomainRubric[];
};

export type CreateRubric201 = DomainResponse & {
  data?: DomainRubric;
};

export type SaveRubricGrade200 = DomainResponse & {
  data?: DomainRubricGrade;
};

export type GetGradesBySubmission200 = DomainResponse & {
  data?: DomainRubricGrade[];
};

export type GetRubricByID200 = DomainResponse & {
  data?: DomainRubric;
};

export type UpdateRubric200 = DomainResponse & {
  data?: DomainRubric;
};

export type StatsGet200 = DomainResponse & {
  data?: DomainStatsResponse;
};

export type TeamGetAllParams = {
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type TeamGetAll200 = DomainResponse & {
  data?: DomainTeam[];
};

export type TeamCreate201 = DomainResponse & {
  data?: DomainTeam;
};

export type TeamGetByID200 = DomainResponse & {
  data?: DomainTeam;
};

export type TeamUpdate200 = DomainResponse & {
  data?: DomainTeam;
};

export type GetMembers200 = DomainResponse & {
  data?: DomainUserResponse[];
};

export type GetAllUsersHandlerParams = {
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type GetAllUsersHandler200 = DomainResponse & {
  data?: DomainUser[];
};

export type GetUserHandler200 = DomainResponse & {
  data?: DomainUserResponse;
};

