/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * MeroEdu API
 * MeroEdu Learning Management System (LMS) API Backend.
 * OpenAPI spec version: 2.0
 */
export interface DomainLearnerStreak {
  currentStreakDays?: number;
  id?: number;
  lastActivityDate?: string;
  longestStreakDays?: number;
  refreshedAt?: number;
  totalActiveDays?: number;
  userId?: number;
}

export interface Data {
  data?: DomainLearnerStreak[];
}

export interface DomainAIGenerationRequest {
  blockType: string;
  context?: string;
  lessonId: number;
  prompt: string;
}

export type DomainAddressType = typeof DomainAddressType[keyof typeof DomainAddressType];


export const DomainAddressType = {
  AddressTypeBilling: 'billing',
  AddressTypeShipping: 'shipping',
  AddressTypeMain: 'main',
  AddressTypeOther: 'other',
} as const;

export interface DomainAddress {
  addressType: DomainAddressType;
  city?: string;
  countryId?: number;
  createdAt?: string;
  id?: number;
  isDefault?: boolean;
  organizationId?: number;
  postalCode?: string;
  state?: string;
  streetAddress1?: string;
  streetAddress2?: string;
  updatedAt?: string;
  userId?: number;
}

export interface DomainAdminResetPasswordRequest {
  /** @minLength 6 */
  newPassword: string;
  userId: number;
}

export interface DomainAssignmentAttachment {
  assignmentId?: number;
  createdAt?: string;
  id?: number;
  mediaId?: number;
}

export interface DomainAssignmentEnrollment {
  assignmentId?: number;
  enrolledAt?: string;
  enrolledBy?: number;
  id?: number;
  userId?: number;
}

export interface DomainAssignmentTeamEnrollment {
  assignmentId?: number;
  enrolledAt?: string;
  enrolledBy?: number;
  id?: number;
  teamId?: number;
}

export interface DomainAttachment {
  courseId?: number;
  createdAt?: string;
  description?: string;
  entityId?: number;
  entityType?: string;
  fileSize?: number;
  fileType?: string;
  id?: number;
  name?: string;
  title?: string;
  updatedAt?: string;
}

export type DomainAttendeeStatus = typeof DomainAttendeeStatus[keyof typeof DomainAttendeeStatus];


export const DomainAttendeeStatus = {
  AttendeeStatusInvited: 'invited',
  AttendeeStatusAccepted: 'accepted',
  AttendeeStatusDeclined: 'declined',
  AttendeeStatusTentative: 'tentative',
  AttendeeStatusAttended: 'attended',
  AttendeeStatusMissed: 'missed',
} as const;

export interface DomainAuditLog {
  action?: string;
  createdAt?: string;
  entityId?: number;
  entityType?: string;
  id?: number;
  ipAddress?: string;
  newValue?: string;
  oldValue?: string;
  organizationId?: number;
  userAgent?: string;
  userId?: number;
}

export interface DomainCategory {
  color?: string;
  courseCount?: number;
  createdAt?: string;
  depth?: number;
  description?: string;
  icon?: string;
  id?: number;
  imageUrl?: string;
  name: string;
  parentId?: number;
  slug?: string;
  sortOrder?: number;
  updatedAt?: string;
}

export type DomainCertificateOrientation = typeof DomainCertificateOrientation[keyof typeof DomainCertificateOrientation];


export const DomainCertificateOrientation = {
  CertificateOrientationLandscape: 'landscape',
  CertificateOrientationPortrait: 'portrait',
} as const;

export interface DomainContentRevision {
  blockId?: string;
  createdAt?: string;
  createdBy?: number;
  id?: number;
  lessonId?: number;
  revision?: number;
  snapshot?: string;
}

export type DomainContentType = typeof DomainContentType[keyof typeof DomainContentType];


export const DomainContentType = {
  ContentTypeMarkdown: 'markdown',
  ContentTypeHTML: 'html',
  ContentTypePlain: 'plain',
} as const;

export type DomainCourseEnrollmentType = typeof DomainCourseEnrollmentType[keyof typeof DomainCourseEnrollmentType];


export const DomainCourseEnrollmentType = {
  open: 'open',
  approval: 'approval',
  invite_only: 'invite_only',
  paid: 'paid',
} as const;

export interface DomainUser {
  addresses?: DomainAddress[];
  avatar?: string;
  bio?: string;
  countryId?: number;
  createdAt?: string;
  deletedAt?: string;
  email?: string;
  emailVerified?: boolean;
  emailVerifiedAt?: string;
  firstname?: string;
  id?: number;
  invitedBy?: number;
  joinedDate?: string;
  lastLoginAt?: string;
  lastname?: string;
  loginCount?: number;
  organizationId?: number;
  password?: string;
  permissions?: string[];
  phone?: string;
  preferredLanguage?: string;
  role?: string;
  roleId?: number;
  status?: string;
  updatedAt?: string;
  username?: string;
}

export interface DomainNullInt64 {
  int64?: number;
  valid?: boolean;
}

export interface DomainLesson {
  contentFormat?: string;
  courseId?: number;
  createdAt?: string;
  displayOrder?: number;
  durationMinutes?: number;
  id?: number;
  isFreePreview?: boolean;
  lessonType?: string;
  status?: number;
  title: string;
  updatedAt?: string;
}

export type DomainStatus = typeof DomainStatus[keyof typeof DomainStatus];


export const DomainStatus = {
  CourseInDraft: 'draft',
  CourseArchived: 'archived',
  CourseAssigned: 'assigned',
  CoursePublished: 'published',
  CoursePublic: 'public',
  CourseCreated: 'created',
  CourseComplete: 'completed',
  StatusSuccess: 'success',
  StatusQueued: 'queued',
  StatusSending: 'sending',
  StatusUnknown: 'unknown',
  StatusScheduled: 'scheduled',
  StatusRetry: 'retrying',
  Success: 'error',
} as const;

export interface DomainCourse {
  attachments?: DomainAttachment[];
  author?: DomainUser;
  authorId?: DomainNullInt64;
  categories?: DomainCategory;
  categoryId?: DomainNullInt64;
  certificateEnabled?: boolean;
  /**
     * @minimum 0
     * @maximum 100
     */
  completionThreshold?: number;
  createdAt?: string;
  deletedAt?: string;
  deletedBy?: number;
  /** @maxLength 5000 */
  description?: string;
  /** @minimum 0 */
  duration?: number;
  enrollmentType?: DomainCourseEnrollmentType;
  featured?: boolean;
  id?: number;
  imageUrl?: string;
  lessonCount?: number;
  lessons?: DomainLesson[];
  status?: DomainStatus;
  /**
     * @minLength 3
     * @maxLength 256
     */
  title: string;
  updatedAt?: string;
  users?: DomainUser[];
  version?: number;
}

export interface DomainCourseInsights {
  activeEnrollments?: number;
  avgProgressPercent?: number;
  avgQuizScore?: number;
  avgTimeSpentSec?: number;
  completedEnrollments?: number;
  courseId?: number;
  id?: number;
  quizPassRate?: number;
  refreshedAt?: number;
  totalEnrollments?: number;
  totalLessonCompletions?: number;
  totalQuizAttempts?: number;
}

export type DomainPrerequisiteType = typeof DomainPrerequisiteType[keyof typeof DomainPrerequisiteType];


export const DomainPrerequisiteType = {
  PrerequisiteTypeRequired: 'required',
  PrerequisiteTypeRecommended: 'recommended',
} as const;

export interface DomainCoursePrerequisite {
  courseId?: number;
  createdAt?: string;
  id?: number;
  prerequisiteCourseId?: number;
  prerequisiteType?: DomainPrerequisiteType;
}

export interface DomainCourseVersion {
  changeLog?: string;
  courseId?: number;
  createdAt?: string;
  createdBy?: number;
  description?: string;
  id?: number;
  snapshot?: string;
  title?: string;
  version?: number;
}

export interface DomainCreateCertificateRequest {
  courseId: number;
  expiresAt?: string;
  grade?: string;
  issuedAt?: string;
  organizationId: number;
  score?: string;
  templateId?: number;
  /**
     * @minLength 1
     * @maxLength 256
     */
  title: string;
  userId: number;
  verificationCode?: string;
}

export interface DomainCreateCertificateTemplateRequest {
  cssStyles?: string;
  htmlTemplate: string;
  isDefault?: boolean;
  /**
     * @minLength 2
     * @maxLength 256
     */
  name: string;
  organizationId: number;
  orientation?: DomainCertificateOrientation;
}

export interface DomainCreateEventAttendeeRequest {
  eventId: number;
  status?: DomainAttendeeStatus;
  userId: number;
}

export type DomainEventType = typeof DomainEventType[keyof typeof DomainEventType];


export const DomainEventType = {
  EventTypeLiveSession: 'live_session',
  EventTypeOfficeHours: 'office_hours',
  EventTypeAssignmentDue: 'assignment_due',
  EventTypeQuizDue: 'quiz_due',
  EventTypeWebinar: 'webinar',
  EventTypeMeeting: 'meeting',
  EventTypeOther: 'other',
} as const;

export interface DomainCreateEventRequest {
  courseId?: number;
  description?: string;
  endTime: string;
  eventType?: DomainEventType;
  isRecurring?: boolean;
  location?: string;
  maxAttendees?: number;
  meetingUrl?: string;
  organizationId: number;
  parentEventId?: number;
  recurrenceRule?: string;
  startTime: string;
  timezone?: string;
  /**
     * @minLength 1
     * @maxLength 256
     */
  title: string;
}

export type DomainForumType = typeof DomainForumType[keyof typeof DomainForumType];


export const DomainForumType = {
  ForumTypeCourse: 'course',
  ForumTypeLesson: 'lesson',
  ForumTypeAnnouncement: 'announcement',
  ForumTypeQA: 'qa',
  ForumTypeOpen: 'open',
} as const;

export interface DomainCreateForumRequest {
  courseId: number;
  description?: string;
  forumType?: DomainForumType;
  isModerated?: boolean;
  lessonId?: number;
  /**
     * @minLength 3
     * @maxLength 256
     */
  title: string;
}

export interface DomainCreateNotificationPreferenceRequest {
  email?: boolean;
  inApp?: boolean;
  notificationType: string;
  push?: boolean;
  userId: number;
}

export type DomainSentVia = typeof DomainSentVia[keyof typeof DomainSentVia];


export const DomainSentVia = {
  SentViaInApp: 'in_app',
  SentViaEmail: 'email',
  SentViaPush: 'push',
} as const;

export type DomainNotificationType = typeof DomainNotificationType[keyof typeof DomainNotificationType];


export const DomainNotificationType = {
  NotificationTypeAssignmentDue: 'assignment_due',
  NotificationTypeGradePosted: 'grade_posted',
  NotificationTypeReply: 'reply',
  NotificationTypeBadge: 'badge',
  NotificationTypeCourseUpdated: 'course_updated',
  NotificationTypeEnrollment: 'enrollment',
  NotificationTypeMention: 'mention',
  NotificationTypeSystem: 'system',
} as const;

export interface DomainCreateNotificationRequest {
  actionUrl?: string;
  body?: string;
  entityId?: number;
  entityType?: string;
  organizationId?: number;
  sentVia?: DomainSentVia[];
  /**
     * @minLength 1
     * @maxLength 256
     */
  title: string;
  type: DomainNotificationType;
  userId: number;
}

export interface DomainCreateReplyRequest {
  content: string;
  contentType?: DomainContentType;
  parentId?: number;
  threadId: number;
}

export interface DomainCreateThreadRequest {
  content: string;
  contentType?: DomainContentType;
  forumId: number;
  /**
     * @minLength 3
     * @maxLength 512
     */
  title: string;
}

export interface DomainDiscussionForum {
  courseId?: number;
  createdAt?: string;
  createdBy?: number;
  description?: string;
  forumType?: DomainForumType;
  id?: number;
  isArchived?: boolean;
  isModerated?: boolean;
  lessonId?: number;
  sortOrder?: number;
  title?: string;
  updatedAt?: string;
}

export interface DomainDiscussionReply {
  attachmentUrls?: string;
  content?: string;
  contentType?: DomainContentType;
  createdAt?: string;
  deletedAt?: string;
  id?: number;
  isAnswer?: boolean;
  parentId?: number;
  threadId?: number;
  updatedAt?: string;
  upvotes?: number;
  userId?: number;
}

export interface DomainDiscussionThread {
  attachmentUrls?: string;
  content?: string;
  contentType?: DomainContentType;
  courseId?: number;
  createdAt?: string;
  deletedAt?: string;
  forumId?: number;
  id?: number;
  isAnswered?: boolean;
  isLocked?: boolean;
  isPinned?: boolean;
  lastReplyAt?: string;
  replyCount?: number;
  title?: string;
  updatedAt?: string;
  upvotes?: number;
  userId?: number;
  viewCount?: number;
}

export type DomainEnrollmentPolicyType = typeof DomainEnrollmentPolicyType[keyof typeof DomainEnrollmentPolicyType];


export const DomainEnrollmentPolicyType = {
  EnrollmentPolicyOpen: 'open',
  EnrollmentPolicyApproval: 'approval',
  EnrollmentPolicyInvite: 'invite_only',
  EnrollmentPolicyPaid: 'paid',
} as const;

export interface DomainEnrollmentPolicy {
  completionCertificate?: boolean;
  courseId?: number;
  createdAt?: string;
  enrollmentEndAt?: number;
  enrollmentStartAt?: number;
  enrollmentType?: DomainEnrollmentPolicyType;
  id?: number;
  isRequiresPrerequisites?: boolean;
  maxEnrollments?: number;
  updatedAt?: string;
  welcomeMessage?: string;
}

export type DomainExportRequestStatus = typeof DomainExportRequestStatus[keyof typeof DomainExportRequestStatus];


export const DomainExportRequestStatus = {
  ExportRequestStatusPending: 'pending',
  ExportRequestStatusProcessing: 'processing',
  ExportRequestStatusCompleted: 'completed',
  ExportRequestStatusFailed: 'failed',
} as const;

export type DomainInvitationRole = typeof DomainInvitationRole[keyof typeof DomainInvitationRole];


export const DomainInvitationRole = {
  InvitationRoleLearner: 'learner',
  InvitationRoleAdmin: 'admin',
  InvitationRoleInstructor: 'instructor',
} as const;

export type DomainInvitationStatus = typeof DomainInvitationStatus[keyof typeof DomainInvitationStatus];


export const DomainInvitationStatus = {
  InvitationStatusPending: 'pending',
  InvitationStatusAccepted: 'accepted',
  InvitationStatusExpired: 'expired',
  InvitationStatusRevoked: 'revoked',
} as const;

export interface DomainInvitation {
  acceptedAt?: string;
  acceptedBy?: number;
  courseId?: number;
  createdAt?: string;
  email?: string;
  expiresAt?: string;
  id?: number;
  invitedBy?: number;
  organizationId?: number;
  role?: DomainInvitationRole;
  status?: DomainInvitationStatus;
  token?: string;
  uuid?: string;
}

export interface DomainLessonBlockRequest {
  lessonId: number;
  snapshot: string;
}

export interface DomainLessonLessonBlock {
  createdAt?: string;
  id?: number;
  lessonId?: number;
  /** JSON snapshot of all blocks */
  snapshot?: string;
  userId?: number;
}

export interface DomainLessonPrerequisite {
  createdAt?: string;
  id?: number;
  lessonId?: number;
  prerequisiteLessonId?: number;
  prerequisiteType?: DomainPrerequisiteType;
}

export interface DomainLoginRequest {
  email: string;
  password: string;
}

export interface DomainUserResponse {
  addresses?: DomainAddress[];
  avatar?: string;
  bio?: string;
  createdAt?: string;
  email?: string;
  emailVerified?: boolean;
  firstName?: string;
  id?: number;
  lastLoginAt?: string;
  lastName?: string;
  loginCount?: number;
  permissions?: string[];
  phone?: string;
  preferredLanguage?: string;
  role?: string;
  status?: string;
  updatedAt?: string;
  username?: string;
}

export interface DomainLoginResponse {
  token?: string;
  user?: DomainUserResponse;
}

export interface DomainMediaFolder {
  createdAt?: string;
  createdBy?: number;
  id?: number;
  name?: string;
  organizationId?: number;
  parentId?: number;
  slug?: string;
}

export interface DomainOrgInsights {
  activeLearners7d?: number;
  activeLearners30d?: number;
  avgCourseProgress?: number;
  completedEnrollments?: number;
  id?: number;
  organizationId?: number;
  publishedCourses?: number;
  refreshedAt?: number;
  totalCourses?: number;
  totalEnrollments?: number;
  totalLearners?: number;
}

export type DomainPaginatedResponse = Data & {
  data?: unknown;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export interface DomainPasswordChangeRequest {
  currentPassword: string;
  /** @minLength 6 */
  newPassword: string;
}

export interface DomainProfileUpdateRequest {
  avatar?: string;
  bio?: string;
  firstName?: string;
  lastName?: string;
  phone?: string;
}

export interface DomainReactionCount {
  count?: number;
  reaction?: string;
}

export interface DomainRegisterRequest {
  email: string;
  firstName: string;
  lastName: string;
  /** @minLength 6 */
  password: string;
  phone?: string;
}

export interface DomainReorderRequest {
  id: number;
  orderNumber: number;
}

export type DomainResponse = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export interface DomainRevokeCertificateRequest {
  /**
     * @minLength 1
     * @maxLength 500
     */
  revokeReason: string;
}

export interface DomainRole {
  code?: string;
  color?: string;
  createdAt?: string;
  description?: string;
  id?: number;
  name?: string;
  permissions?: string[];
  updatedAt?: string;
}

export interface DomainRubricLevel {
  criteriaId?: number;
  id?: number;
  points?: number;
  sortOrder?: number;
  title: string;
}

export interface DomainRubricCriteria {
  description?: string;
  id?: number;
  levels?: DomainRubricLevel[];
  maxPoints?: number;
  rubricId?: number;
  sortOrder?: number;
  title: string;
}

export interface DomainRubric {
  createdAt?: string;
  createdBy?: number;
  criteria?: DomainRubricCriteria[];
  description?: string;
  id?: number;
  isTemplate?: boolean;
  maxPoints?: number;
  organizationId?: number;
  title: string;
  updatedAt?: string;
}

export interface DomainRubricGrade {
  criteriaId?: number;
  feedback?: string;
  id?: number;
  levelId?: number;
  points?: number;
  submissionId?: number;
}

export interface DomainStatsResponse {
  categoryCount?: number;
  courseCount?: number;
  teamCount?: number;
  userCount?: number;
}

export type DomainSubmissionStatus = typeof DomainSubmissionStatus[keyof typeof DomainSubmissionStatus];


export const DomainSubmissionStatus = {
  SubmissionSubmitted: 'submitted',
  SubmissionGraded: 'graded',
  SubmissionReturned: 'returned',
} as const;

/**
 * USER or TEAM
 */
export type DomainSubmissionType = typeof DomainSubmissionType[keyof typeof DomainSubmissionType];


export const DomainSubmissionType = {
  SubmissionTypeUser: 'user',
  SubmissionTypeTeam: 'team',
} as const;

export interface DomainSubmission {
  assignmentId?: number;
  /** comma-separated file URLs */
  attachmentURLs?: string;
  attemptNumber?: number;
  /** text content or file URLs */
  content?: string;
  feedback?: string;
  gradedAt?: string;
  gradedBy?: number;
  id?: number;
  isLate?: boolean;
  score?: number;
  status?: DomainSubmissionStatus;
  submissionType?: DomainSubmissionType;
  submittedAt?: string;
  submittedBy?: number;
  teamId?: number;
  user?: DomainUser;
  userId?: number;
}

export interface DomainSummaries {
  data?: unknown;
  message?: DomainStatus;
  total?: number;
}

export interface DomainTeam {
  color?: string;
  createdAt?: string;
  description?: string;
  id?: number;
  imageUrl?: string;
  member_count?: number;
  name?: string;
  organizationId?: number;
  roleId?: number;
  status?: number;
  updatedAt?: string;
}

export interface DomainTeamMember {
  avatar?: string;
  createdAt?: string;
  id?: number;
  role?: string;
  teamId?: number;
  userEmail?: string;
  userId?: number;
  userName?: string;
}

export interface DomainThreadListResponse {
  limit?: number;
  page?: number;
  threads?: DomainDiscussionThread[];
  total?: number;
  totalPages?: number;
}

export interface DomainUpdateCertificateRequest {
  expiresAt?: number;
  grade?: string;
  isRevoked?: boolean;
  pdfUrl?: string;
  revokeReason?: string;
  score?: string;
  templateId?: number;
  title?: string;
}

export interface DomainUpdateCertificateTemplateRequest {
  cssStyles?: string;
  htmlTemplate?: string;
  isDefault?: boolean;
  name?: string;
  orientation?: DomainCertificateOrientation;
}

export interface DomainUpdateDataExportRequest {
  completedAt?: string;
  expiresAt?: string;
  fileUrl?: string;
  status?: DomainExportRequestStatus;
}

export interface DomainUpdateEventAttendeeRequest {
  status: DomainAttendeeStatus;
}

export interface DomainUpdateEventRequest {
  description?: string;
  endTime?: string;
  eventType?: DomainEventType;
  isRecurring?: boolean;
  location?: string;
  maxAttendees?: number;
  meetingUrl?: string;
  recurrenceRule?: string;
  startTime?: string;
  timezone?: string;
  title?: string;
}

export interface DomainUpdateNotificationPreferenceRequest {
  email?: boolean;
  inApp?: boolean;
  push?: boolean;
}

export type DomainWaitlistStatus = typeof DomainWaitlistStatus[keyof typeof DomainWaitlistStatus];


export const DomainWaitlistStatus = {
  WaitlistStatusWaiting: 'waiting',
  WaitlistStatusInvited: 'invited',
  WaitlistStatusEnrolled: 'enrolled',
  WaitlistStatusExpired: 'expired',
} as const;

export interface DomainWaitlistEntry {
  courseId?: number;
  createdAt?: string;
  expiresAt?: string;
  id?: number;
  invitedAt?: string;
  position?: number;
  status?: DomainWaitlistStatus;
  userId?: number;
}

export interface HttpAdminEnrollRequest {
  userId: number;
}

export interface HttpAdminEnrollTeamRequest {
  teamId: number;
}

export interface HttpCompleteRequest {
  /** @minimum 0 */
  timeSpentSeconds?: number;
}

export interface HttpErrorDetail {
  constraint?: string;
  field?: string;
  message?: string;
}

export interface HttpResponseError {
  code?: string;
  details?: HttpErrorDetail[];
  message?: string;
}

export type GetCourseInsights200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetOrgInsights200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type ListTopStreaksParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type ListTopStreaks200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetLearnerStreak200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GenerateContentBody = { [key: string]: unknown } | DomainAIGenerationRequest;

export type GetAttachmentsBody = { [key: string]: unknown };

export type GetAttachments200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type AddAttachmentBody = { [key: string]: unknown };

export type EnrollTeamBody = { [key: string]: unknown };

export type RemoveTeamEnrollmentBody = { [key: string]: unknown };

export type EnrollUserBody = { [key: string]: unknown };

export type RemoveUserEnrollmentBody = { [key: string]: unknown };

export type GetEnrolledTeamsBody = { [key: string]: unknown };

export type GetEnrolledTeams200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetEnrolledUsersBody = { [key: string]: unknown };

export type GetEnrolledUsers200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type AssignmentPublishBody = { [key: string]: unknown };

export type AssignmentSubmitBody = { [key: string]: unknown };

export type AssignmentSubmit201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type SubmitTeamBody = { [key: string]: unknown };

export type SubmitTeam201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type DeleteAttachmentBody = { [key: string]: unknown };

export type GetSubmissionByIDBody = { [key: string]: unknown };

export type GetSubmissionByID200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type AssignmentGradeBody = { [key: string]: unknown };

export type GradeTeamBody = { [key: string]: unknown };

export type GetAllAttachmentsParams = {
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type GetAllAttachments200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type DownloadAttachmentParams = {
/**
 * uuid-encoded file name
 */
file: string;
};

export type GetAuditLogsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
/**
 * Filter by user ID
 */
userId?: number;
/**
 * Filter by organization ID
 */
orgId?: number;
/**
 * Filter by entity type
 */
entityType?: string;
/**
 * Filter by entity ID
 */
entityId?: number;
/**
 * Filter by action
 */
action?: string;
};

export type CreateAuditLogBody = { [key: string]: unknown } | DomainAuditLog;

export type CreateDataExportRequestBody = { [key: string]: unknown };

export type UpdateDataExportRequestBody = { [key: string]: unknown } | DomainUpdateDataExportRequest;

export type AdminResetPasswordHandlerBody = { [key: string]: unknown } | DomainAdminResetPasswordRequest;

export type LoginHandlerBody = { [key: string]: unknown } | DomainLoginRequest;

export type LoginHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type MeHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type ChangePasswordHandlerBody = { [key: string]: unknown } | DomainPasswordChangeRequest;

export type UpdateProfileHandlerBody = { [key: string]: unknown } | DomainProfileUpdateRequest;

export type UpdateProfileHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type RegisterHandlerBody = { [key: string]: unknown } | DomainRegisterRequest;

export type RegisterHandler201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetBlockVersions200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CategoryGetAllParams = {
/**
 * Search by name
 */
search?: string;
/**
 * Offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type CategoryGetAllBody = { [key: string]: unknown };

export type CategoryCreateBody = { [key: string]: unknown } | DomainCategory;

export type CategoryDeleteBody = { [key: string]: unknown };

export type CategoryGetByIDBody = { [key: string]: unknown };

export type CategoryUpdateBody = { [key: string]: unknown } | DomainCategory;

export type CategorySetParentBody = { [key: string]: unknown } | {
  parentId?: number;
};

export type CategoryGetChildrenParams = {
/**
 * Offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type CategoryGetChildrenBody = { [key: string]: unknown };

export type CategoryGetRootsParams = {
/**
 * Offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type CategoryGetRootsBody = { [key: string]: unknown };

export type GetUserCertificatesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type IssueCertificateBody = { [key: string]: unknown } | DomainCreateCertificateRequest;

export type CertificateUpdateBody = { [key: string]: unknown } | DomainUpdateCertificateRequest;

export type RevokeCertificateBody = { [key: string]: unknown } | DomainRevokeCertificateRequest;

export type GetCourseCertificatesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetOrgCertificatesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type CreateTemplateBody = { [key: string]: unknown } | DomainCreateCertificateTemplateRequest;

export type UpdateTemplateBody = { [key: string]: unknown } | DomainUpdateCertificateTemplateRequest;

export type CreateCoursePrerequisiteBody = { [key: string]: unknown } | DomainCoursePrerequisite;

export type CreateCoursePrerequisite201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetCoursePrerequisitesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
pageSize?: number;
};

export type GetCoursePrerequisites200 = Data & {
  data?: unknown;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export type CreateLessonPrerequisiteBody = { [key: string]: unknown } | DomainLessonPrerequisite;

export type CreateLessonPrerequisite201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetLessonPrerequisitesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
pageSize?: number;
};

export type GetLessonPrerequisites200 = Data & {
  data?: unknown;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export type CreateContentRevisionBody = { [key: string]: unknown } | DomainContentRevision;

export type CreateContentRevision201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetContentRevision200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetBlockRevisionsParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetBlockRevisions200 = Data & {
  data?: unknown;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export type GetLatestContentRevision200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetLessonRevisionsParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetLessonRevisions200 = Data & {
  data?: unknown;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export type CreateCourseVersionBody = { [key: string]: unknown } | DomainCourseVersion;

export type CreateCourseVersion201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetCourseVersion200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetCourseVersionsParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};

export type GetCourseVersions200 = Data & {
  data?: unknown;
  hasNext?: boolean;
  hasPrev?: boolean;
  message?: DomainStatus;
  page?: number;
  pageSize?: number;
  total?: number;
  totalPages?: number;
};

export type GetLatestCourseVersion200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CourseGetAllParams = {
/**
 * start
 */
start: number;
/**
 * limit
 */
limit: number;
};

export type CourseCreateBody = { [key: string]: unknown } | DomainCourse;

export type CourseUpdateBody = { [key: string]: unknown } | DomainCourse;

export type EnrollmentAdminEnrollTeamBody = { [key: string]: unknown } | HttpAdminEnrollTeamRequest;

export type EnrollmentAdminEnrollUserBody = { [key: string]: unknown } | HttpAdminEnrollRequest;

export type EnrollmentDropBody = { [key: string]: unknown };

export type EnrollmentEnrollBody = { [key: string]: unknown };

export type CreateLessonForCourseBody = { [key: string]: unknown } | DomainLesson;

export type ReorderLessonsBody = { [key: string]: unknown } | DomainReorderRequest[];

export type UpdateCourseStatusBodyOne = { [key: string]: unknown };

export type UpdateCourseStatus200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetCourseForums200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateForumBody = { [key: string]: unknown } | DomainCreateForumRequest;

export type CreateForum201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetForumThreadsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Thread limit per page
 */
limit?: number;
};

export type GetForumThreads200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateThreadBody = { [key: string]: unknown } | DomainCreateThreadRequest;

export type CreateThread201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type SearchThreadsParams = {
/**
 * Search query string
 */
q: string;
/**
 * Page number
 */
page?: number;
/**
 * Page size
 */
limit?: number;
};

export type SearchThreads200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetForum200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateForumBody = { [key: string]: unknown } | DomainDiscussionForum;

export type UpdateForum200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type RemoveReactionBody = { [key: string]: unknown } | {[key: string]: unknown};

export type ReactBody = { [key: string]: unknown } | {[key: string]: unknown};

export type GetReactions200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetReply200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateReplyBody = { [key: string]: unknown } | DomainDiscussionReply;

export type UpdateReply200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type MarkAsAnswerParams = {
/**
 * Is it correct answer
 */
isAnswer: boolean;
};

export type UnsubscribeBody = { [key: string]: unknown } | {[key: string]: unknown};

export type SubscribeBody = { [key: string]: unknown } | {[key: string]: unknown};

export type GetThread200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateThreadBody = { [key: string]: unknown } | DomainDiscussionThread;

export type UpdateThread200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type LockThreadParams = {
/**
 * Locked status
 */
lock: boolean;
};

export type PinThreadParams = {
/**
 * Pinned status
 */
pin: boolean;
};

export type GetThreadRepliesParams = {
/**
 * Page number
 */
page?: number;
/**
 * Limit number
 */
limit?: number;
};

export type GetThreadReplies200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateReplyBody = { [key: string]: unknown } | DomainCreateReplyRequest;

export type CreateReply201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type VoteBody = { [key: string]: unknown } | {[key: string]: unknown};

export type CreateInvitationBody = { [key: string]: unknown } | DomainInvitation;

export type CreateInvitation201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetInvitationsByCourse200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetPendingInvitationsByEmail200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetInvitationByToken200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetInvitationByUUID200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateEnrollmentPolicyBody = { [key: string]: unknown } | DomainEnrollmentPolicy;

export type CreateEnrollmentPolicy201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetEnrollmentPolicy200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateEnrollmentPolicyBody = { [key: string]: unknown } | DomainEnrollmentPolicy;

export type UpdateEnrollmentPolicy200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateWaitlistEntryBody = { [key: string]: unknown } | DomainWaitlistEntry;

export type CreateWaitlistEntry201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetWaitlist200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type InviteWaitlist200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetOrgEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type EventCreateBody = { [key: string]: unknown } | DomainCreateEventRequest;

export type GetEventAttendeesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type AddAttendeeBody = { [key: string]: unknown } | DomainCreateEventAttendeeRequest;

export type UpdateAttendeeStatusBody = { [key: string]: unknown } | DomainUpdateEventAttendeeRequest;

export type EventUpdateBody = { [key: string]: unknown } | DomainUpdateEventRequest;

export type GetCourseEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetEventsInTimeRangeParams = {
/**
 * Start time (Unix timestamp)
 */
startTime: number;
/**
 * End time (Unix timestamp)
 */
endTime: number;
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetEventsByTypeParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetUpcomingEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetUserEventsParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type GetUserAttendeesParams = {
/**
 * start
 */
start?: number;
/**
 * limit
 */
limit?: number;
};

export type LessonGetAllParams = {
/**
 * start
 */
start: number;
/**
 * limit
 */
limit: number;
};

export type LessonCreateBody = { [key: string]: unknown } | DomainLesson;

export type LessonUpdateBody = { [key: string]: unknown } | DomainLesson;

export type LessonBlockBody = { [key: string]: unknown } | DomainLessonBlockRequest;

export type UploadBlockMediaBodyTwo = { [key: string]: unknown };

export type MarkCompleteBody = { [key: string]: unknown } | HttpCompleteRequest;

export type UploadLessonMediaBodyTwo = { [key: string]: unknown };

export type GetFoldersParams = {
/**
 * Parent folder ID for nested folders
 */
parentId?: number;
};

export type CreateFolderBody = { [key: string]: unknown } | DomainMediaFolder;

export type UpdateFolderBody = { [key: string]: unknown } | DomainMediaFolder;

export type MediaUploadBodyTwo = { [key: string]: unknown };

export type NotificationCreateBody = { [key: string]: unknown } | DomainCreateNotificationRequest;

export type CreatePreferenceBody = { [key: string]: unknown } | DomainCreateNotificationPreferenceRequest;

export type UpdatePreferenceBody = { [key: string]: unknown } | DomainUpdateNotificationPreferenceRequest;

export type GetAllRolesHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateRoleHandlerBody = { [key: string]: unknown } | DomainRole;

export type CreateRoleHandler201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetRoleByIDHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateRoleHandlerBody = { [key: string]: unknown } | DomainRole;

export type UpdateRoleHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type ListRubricsParams = {
/**
 * Limit results
 */
limit?: number;
/**
 * Offset results
 */
offset?: number;
};

export type ListRubrics200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type CreateRubricBody = { [key: string]: unknown } | DomainRubric;

export type CreateRubric201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetRubricByID200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateRubricBody = { [key: string]: unknown } | DomainRubric;

export type UpdateRubric200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type SaveRubricGradeBody = { [key: string]: unknown } | DomainRubricGrade;

export type SaveRubricGrade200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetGradesBySubmission200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type StatsGet200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type TeamGetAllParams = {
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type TeamGetAll200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type TeamCreateBody = { [key: string]: unknown } | DomainTeam;

export type TeamCreate201 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type TeamGetByID200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type TeamUpdateBody = { [key: string]: unknown } | DomainTeam;

export type TeamUpdate200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetAvailableUsersParams = {
/**
 * Search by name or email
 */
search?: string;
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type GetAvailableUsers200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetMembers200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type AddMemberBody = { [key: string]: unknown } | DomainTeamMember;

export type GetAllUsersHandlerParams = {
/**
 * Pagination offset
 */
start?: number;
/**
 * Page size
 */
limit?: number;
};

export type GetAllUsersHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type GetUserHandler200 = Data & {
  data?: unknown;
  message?: DomainStatus;
};

export type UpdateUserHandlerBody = { [key: string]: unknown } | DomainUser;

